Cats_99/config/routes.rb
Rails.application.routes.draw do

#   Prefix Verb  URI Pattern              Controller#Action
#     cats GET   /cats(.:format)          cats#index
#          POST  /cats(.:format)          cats#create
#  new_cat GET   /cats/new(.:format)      cats#new
# edit_cat GET   /cats/:id/edit(.:format) cats#edit
#      cat GET   /cats/:id(.:format)      cats#show
#          PATCH /cats/:id(.:format)      cats#update
#          PUT   /cats/:id(.:format)      cats#update

# cat_rental_requests GET   /cat_rental_requests(.:format)          cat_rental_requests#index
#                         POST  /cat_rental_requests(.:format)          cat_rental_requests#create
#  new_cat_rental_request GET   /cat_rental_requests/new(.:format)      cat_rental_requests#new
# edit_cat_rental_request GET   /cat_rental_requests/:id/edit(.:format) cat_rental_requests#edit
#      cat_rental_request GET   /cat_rental_requests/:id(.:format)      cat_rental_requests#show
#                         PATCH /cat_rental_requests/:id(.:format)      cat_rental_requests#update
#                         PUT   /cat_rental_requests/:id(.:format)      cat_rental_requests#update


  resources :cats, only: [:index, :show, :new, :create, :edit, :update]

  resources :cat_rental_requests, only: [:index, :show, :new, :create, :edit, :update]
end

Cats_99/app/models/cat.rb
require 'date'
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ActiveRecord::Base

  validates :name, presence: true
  validates :color, presence: true
  validates :birth_date, presence: true
  validates :sex, presence: true

  has_many :requests,
  dependent: :destroy,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :CatRentalRequest

  def age
    birth = Date.parse("2014/05/19")
    now = Time.now.to_date
    age = now.year - birth.year
    # age_month = now.month - birth.month
    age
  end
end

Cats_99/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base

  validates :cat_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true, inclusion: {
    in: ["APPROVED", "DENIED", "PENDING"],
    message: "%{status} is not valid"
  }
  # validates :status, presence: true

  belongs_to :cat,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :Cat

  def overlapping_requests

  end

  def overlapping_approved_requests

  end

end

Cats_99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

Cats_99/app/controllers/cat_rental_requests_controller.rb
# cat_rental_requests GET   /cat_rental_requests(.:format)          cat_rental_requests#index
#                         POST  /cat_rental_requests(.:format)          cat_rental_requests#create
#  new_cat_rental_request GET   /cat_rental_requests/new(.:format)      cat_rental_requests#new
# edit_cat_rental_request GET   /cat_rental_requests/:id/edit(.:format) cat_rental_requests#edit
#      cat_rental_request GET   /cat_rental_requests/:id(.:format)      cat_rental_requests#show
#                         PATCH /cat_rental_requests/:id(.:format)      cat_rental_requests#update
#                         PUT   /cat_rental_requests/:id(.:format)      cat_rental_requests#update


class CatRentalRequestsController < ApplicationController

  def index
    @requests = CatRentalRequest.all
    render :index
  end

  def show
    @request = CatRentalRequest.find_by(id: params[:id])
  end

  def new
    @request = CatRentalRequest.new
    render :new
  end

  def create
    @request = CatRentalRequest.new(request_param)
    if @request.save
      redirect_to cat_rental_request_url(@request)
    else
      render :new
    end
  end

  private

  def request_param
    params.require(:request).permit(:cat_id, :start_date, :end_date)
  end
end

Cats_99/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_param)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update_attributes(cat_param)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end


  private

  def cat_param
    params.require(:cat).permit(:name, :color, :birth_date, :sex)
  end

end

Cats_99/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats_99/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

Cats_99/app/helpers/cats_helper.rb
module CatsHelper
end

Cats_99/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>


<form action= '<%= action_url %>' method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value= "<%=cat.name%>">
  <br>
  <br>

  <label for="birth_date">Birth Date</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value= "<%=cat.birth_date%>">
  <br>
  <br>

  debugger
  <label for="color">Color</label>
  <select id = "color" name="cat[color]">
    <option disabled <%= cat.color ? "" : "selected"%> >Select a color</option>
    <option value="black" <%= cat.color == "black" ? "selected" : ""%> >black</option>
    <option value="white" <%= cat.color == "white" ? "selected" : ""%> >white</option>
    <option value="orange" <%= cat.color == "orange" ? "selected" : ""%> >orange</option>
    <option value="brown" <%= cat.color == "brown" ? "selected" : ""%> >brown</option>
  </select>
  <br>
  <br>

  <label for="sex">Sex</label>
  <br>
  <input id="sex" type="radio" name="cat[sex]" value= "M" <%= cat.sex == "M" ? "checked" : ""%>>Male<br>
  <input id="sex" type="radio" name="cat[sex]" value= "F" <%= cat.sex == "F" ? "checked" : ""%>>Female<br>
  <br>
  <br>


  <input type="submit" value="Submit edit">


</form>

Cats_99/app/views/cats/edit.html.erb
<h1>Edit Cat</h1>

<%= render 'form', action: :edit, cat: @cat %>

Cats_99/app/views/cats/index.html.erb
<h1>All cats!</h1>

<ul>
  <% @cats.each do |cat|  %>
  <li><%= link_to "#{cat.name}", cat_url(cat) %></li>
  <% end %>
</ul>

<%= button_to "Add cat", new_cat_url, method: :get %>

Cats_99/app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', action: :new, cat: @cat %>

<!-- <form action= '<%= cats_url %>' method="post">

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]">

  <label for="birth_date">Birth Date</label>
  <input id="birth_date" type="date" name="cat[birth_date]">

  <label for="color">Color</label>
  <select id = "color" name="cat[color]">
    <option disabled selected>Select a color</option>
    <option value="black">black</option>
    <option value="white">white</option>
    <option value="orange">orange</option>
    <option value="brown">brown</option>
  </select>

  <label for="sex">Sex</label>
  <input id="sex" type="text" name="cat[sex]">

  <input type="submit" value="Add new cat">


</form> -->

Cats_99/app/views/cats/show.html.erb
<img src="https://i.ytimg.com/vi/cNycdfFEgBc/maxresdefault.jpg" height="200" width="250">
<br>
<h1><%=@cat.name %></h1>
<br>
<table>
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr>
    <tr>
      <td>age<td>
      <td><%= @cat.age %></td>
    </tr>
    <tr>
      <td>Birth Date</td>
      <td> <%= @cat.birth_date %></td>
    </tr>
    <tr>
      <td>Color</td>
      <td><%= @cat.color %></td>
    </tr>
    <tr>
      <td>Sex</td>
      <td><%= @cat.sex %></td>
    </tr>
</table>
<br>
<br>
<%= button_to "Edit Cat", edit_cat_url(@cat), method: :get %>
<br>
<br>
<%= button_to "Cat list", cats_url, method: :get %>


<!-- <table>
    <tr>
      <th>Attribute</th>
      <th>Value</th>
    </tr>
      <tr>
        <td>age</td>
        <td>almost 7 years</td>
      </tr>
      <tr>
        <td>birth_date</td>
        <td>2010-02-03</td>
      </tr>
      <tr>
        <td>color</td>
        <td>black</td>
      </tr>
      <tr>
        <td>sex</td>
        <td>F</td>
      </tr>
  </table> -->

Cats_99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>